FROM node:20

WORKDIR /app

COPY package*.json ./
COPY frontend/package*.json ./frontend/

RUN npm install

COPY frontend ./frontend
COPY shared ./shared

WORKDIR /app/frontend

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

EXPOSE 3000

CMD ["npm", "run", "dev"]