services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/giveapp
      - JWT_SECRET=${JWT_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
    volumes:
      - ./shared:/app/shared
    depends_on:
      - mongodb

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    volumes:
      - ./shared:/app/shared
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

volumes:
  mongodb_data: