services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:${MONGODB_PORT:-27017}/giveapp
      - JWT_SECRET=${JWT_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
    volumes:
      - ./shared:/app/shared
    depends_on:
      - mongodb

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    volumes:
      - ./shared:/app/shared
    depends_on:
      - backend

  mongodb:
    image: mongo:4.0
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
  
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-5000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
    ports:
      - "${PUBLIC_PORT:-80}:80"
    depends_on:
      - frontend

volumes:
  mongodb_data: