FROM node:20

WORKDIR /app

ENV BACKEND_PORT=5000

COPY package*.json ./
COPY backend/package*.json ./backend/

RUN npm install

COPY backend ./backend
COPY shared ./shared

WORKDIR /app/backend

EXPOSE 5000

CMD ["npm", "run", "dev"]